name: Anim
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Pyrogram
        run: |
          pip install pyrofork && pip install tgcrypto
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Cd Into Repo
        run: |
          cd ${{ github.workspace }}
      - name: Running the Script 
        run: |
          python caption.py
